Разметка страниц Седоны
htmlacademy-htmlcss/1060227-sedona-1 pull request #2
Opened 2023-10-12 20:51 UTC by aaaasmirnova

2023-10-13 08:06 UTC, DoberBober commented on catalog.html
> +            </div> -->  <!--пока не могу разобраться, получилось два ползунка, не понимаю как их объединить и связать с окошками для ввода цен-->
Никак.)
Сделай див, в котором две кнопки и ещё один див. Кнопки для ползунков, див для полоски.

2023-10-13 08:06 UTC, DoberBober commented on catalog.html
> +        </a>
Оберни всё в див, чтобы сгруппировать.

2023-10-13 08:06 UTC, DoberBober commented on catalog.html
> +            <h3 class="hotel-card-title">Amara Resort & Spa</h3>
```suggestion
            <a><img class="hotel-card-image" src="#" alt="Amara Resort & Spa"></a>
            <h3 class="hotel-card-title"><a>Amara Resort & Spa</a></h3>
```

2023-10-13 08:07 UTC, DoberBober commented on catalog.html
> +            <button class="button hotel-to-favourites-button" type="submit">В избранное</button>
Ссылка.

2023-10-13 08:08 UTC, DoberBober requested changes
Очень хорошо. Есть пара правок, но это прям мелочь.
Молодец.

2023-10-13 10:22 UTC, aaaasmirnova commented on catalog.html
> +            <h3 class="hotel-card-title">Amara Resort & Spa</h3>
А здесь нужно добавлять класс ссылке?

2023-10-13 10:25 UTC, aaaasmirnova commented on catalog.html
> +            <button class="button hotel-to-favourites-button" type="submit">В избранное</button>
Вот так правильнее? <a class="hotel-card-detail-link" href="#">Подробнее</a>

2023-10-13 10:26 UTC, aaaasmirnova commented on catalog.html
> +            <button class="button hotel-to-favourites-button" type="submit">В избранное</button>
Вбила тег в комментарии, но он пропал. в ссылке убрать button получается?

2023-10-13 10:44 UTC, aaaasmirnova commented on catalog.html
> +            </div> -->  <!--пока не могу разобраться, получилось два ползунка, не понимаю как их объединить и связать с окошками для ввода цен-->
Тут я не догоняю. Прям просто две кнопки button?

2023-10-13 13:41 UTC, DoberBober commented on catalog.html
> +            </div> -->  <!--пока не могу разобраться, получилось два ползунка, не понимаю как их объединить и связать с окошками для ввода цен-->
Ага.
```
<div class="range">
    <div class="line"></div>
    <button type="button"><button>
    <button type="button"><button>
</div>
```

2023-10-13 13:42 UTC, DoberBober commented on catalog.html
> +            <button class="button hotel-to-favourites-button" type="submit">В избранное</button>
`<a class="button hotel-to-favourites-button" href="#">В избранное</a>`.

2023-10-13 13:44 UTC, DoberBober commented on catalog.html
> +            <h3 class="hotel-card-title">Amara Resort & Spa</h3>
Классы, скорее всего, тебе пригодятся. Можешь сразу добавить.

Я, когда привожу пример, редко классы пишу. Просто чтобы пример не раздувался и ты видела саму структуру. А добавлять или нет и, если добавлять, то какие - это уже ты решай.

2023-10-13 20:10 UTC, aaaasmirnova commented on catalog.html
> +            </div> -->  <!--пока не могу разобраться, получилось два ползунка, не понимаю как их объединить и связать с окошками для ввода цен-->
Сложно дается мне этот момент, я добавила часть кода из комментария выше, с этим пока больше ничего не нужно делать?

2023-10-14 17:01 UTC, DoberBober commented on catalog.html
> +            </div> -->  <!--пока не могу разобраться, получилось два ползунка, не понимаю как их объединить и связать с окошками для ввода цен-->
Да, этого пока достаточно. С формами ты будешь работать в конце курса, поэтому пока не переживай, что не понятно.

2023-10-15 08:26 UTC, aaaasmirnova commented on catalog.html
> +            </div> -->  <!--пока не могу разобраться, получилось два ползунка, не понимаю как их объединить и связать с окошками для ввода цен-->
Хорошо

2023-10-15 16:33 UTC, DoberBober approved these changes
lgtm.

2023-10-15 16:34 UTC, merged