Базовая стилизация
htmlacademy-htmlcss/1060227-sedona-1 pull request #4
Opened 2023-10-28 20:12 UTC by aaaasmirnova

2023-10-28 20:30 UTC, DoberBober commented on index.html
> +              <h3 class="advantages-title advantages-title-white">Настоящий городок</h3>
А зачем все эти лишние дивы? Можно ж сами лишки оформить.
(Критерий на лишние элементы не пройдёшь с ними.)

2023-10-28 20:31 UTC, DoberBober commented on index.html
> +            <div class="advantages-container">
А зачем все эти лишние дивы? Можно ж сами лишки оформить. В первой и последней лишке - оправдано, используется для отделения текста от картинки. В остальных не нужно.
(Критерий на лишние элементы не пройдёшь с ними.)

2023-10-28 20:34 UTC, DoberBober requested changes
Лишние дивы убери лучше сразу, а то потом тяжело будет их выкорчевывать.
И после, отправки задания, нажимай, пожалуйста, кнопку "Опубликовать".
<img width="319" alt="image" src="https://github.com/htmlacademy-htmlcss/1060227-sedona-1/assets/18398812/d79acdd2-df4d-4ef1-ab91-ea8da475a5e6">

2023-10-29 13:17 UTC, aaaasmirnova commented on index.html
> +            <div class="advantages-container">
Хорошо, оставила только в первой и последней.

2023-10-29 15:17 UTC, merged