Сетки компонентов на флексах
htmlacademy-htmlcss/1060227-sedona-1 pull request #6
Opened 2023-11-13 19:31 UTC by aaaasmirnova

2023-11-13 20:40 UTC, DoberBober requested changes
1. `.advantages-content-title` и `.advantages-content-description` - `max-width`, который должен быть и `margin-left/right: auto`, а `padding`-и удали. Так у тебя получится универсальное центрирование, которое не зависит от ширины контейнера.
2. Аналогично у `.recommendations-content-title` и `.recommendations-content-description`.
3. У `.search-container` удали паддинги слева и справа и замени на `margin-left/right: auto`.
4. У `.footer-contacts` удали паддинги. Вместо этого укажи у `.page-footer-container` `justify-content: space-between`.
5. Решение с `.hotel-card:nth-child(3n)` хорошее, молодец. Обычно студенты не догадываются указывать `n`. Но можно написать проще, удалив маргин у карточек и указав `gap: 30px` у `.hotel-list`.
6. И у `body`, я думаю, можно уже указать ширину и тень по краям.

2023-11-14 13:02 UTC, aaaasmirnova commented
А вот ширину body как правильнее указать? 1200 и padding left/right: 40px? или 1280px?

2023-11-14 13:09 UTC, aaaasmirnova commented
Еще я с фоновым цветом запуталась. Получается для body нужно указать background: #F2F2F2;, а для page-header, page-container, page-footer fffff?

2023-11-14 13:17 UTC, aaaasmirnova commented
А, наверное, если у меня ширина page-container 1200 указана, то для body можно указать 1280?

2023-11-14 13:21 UTC, aaaasmirnova commented
И еще вопрос по тени, в моем случае правильнее будет обернуть шапку, подвал и main в див и задать этому div тень?

2023-11-14 15:22 UTC, DoberBober commented
У `body` укажи ширину 1200 и задай тень и белый фоновый цвет.
А для `html` задай серый фоновый цвет.

Если у пользователя будет маленький экран, то он будет видеть только контент, тень ему никчему. А если большой - серый фон и тень.

2023-11-14 18:01 UTC, aaaasmirnova commented
![Седона](https://github.com/htmlacademy-htmlcss/1060227-sedona-1/assets/146733235/9e2a40ca-6b9e-4b91-a7fd-545908b27149)

Если для html задаю фон, то сайт прилипает к левой стороне, а фон серым окрашивается справа

2023-11-14 20:46 UTC, DoberBober commented
У `body` добавить `margin 0 auto`.

2023-11-15 20:15 UTC, merged